seed: 42


dataset_args:
  target_size: 768
  normalize_depth: marigold
  pixel_mean: [127.5, 127.5, 127.5]
  pixel_std: [127.5, 127.5, 127.5]
  src_list:
    - sample_list: workspace/datasets/live2d_bodysamples_chunk0_complete.txt
    - sample_list: workspace/datasets/live2d_bodysamples_chunk12_complete.txt
    - sample_list: workspace/datasets/live2d_bodysamples_chunk5_complete.txt

  random_flip: 0.5
  random_crop: 0.3
  random_pad_prob: 0.5
  random_hsv: 0.25
  # depth_cond_prob: 1.
  # load_depth_cond: true

  pad_argb: false
  include_blend_cls: true
  tag_list: [
    'hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 
    'neck', 'neckwear', 'topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 
    'tail', 'wings', 'objects'
  ]
  mix_tag_groups:
    - tags: ['hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear']
      random_tag_prob: 0.
      size_skip_tags: ['hair']
    - tags: ['topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 'tail', 'wings', 'objects']
      random_tag_prob: 0.
      cond_tags: ['hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear']
    - tags: ['hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear', 'topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 'tail', 'wings', 'objects']
      random_tag_prob: 0.

valset_args:
  target_size: 768
  normalize_depth: marigold
  pixel_mean: [127.5, 127.5, 127.5]
  pixel_std: [127.5, 127.5, 127.5]

  pad_argb: false
  include_blend_cls: true

  mix_tag_groups:
    # - tags: ['hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear']
    #   random_tag_prob: 0.
    #   size_skip_tags: ['hair']
    # - tags: ['topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 'tail', 'wings', 'objects']
    #   random_tag_prob: 0.
    #   cond_tags: ['hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear']
    - tags: ['hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear', 'topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 'tail', 'wings', 'objects']
      random_tag_prob: 0.

  src_list:
    - workspace/datasets/live2d_bodysamples_chunk3_complete.txt
  tag_list: [
    'hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 
    'neck', 'neckwear', 'topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 
    'tail', 'wings', 'objects'
  ]

  # depth_cond_prob: 1.
  # load_depth_cond: true

# model_args:
#   model_type: h_hq
#   fix_img_en: false
#   fix_prompt_en: true
#   fix_mask_de: false
#   class_num: 19

optimizer_args:
  betas: [0.9, 0.999]
  weight_decay: 0.1
  eps: 1e-08


validation_steps: 2500
checkpointing_steps: 2500
visualization_steps: 125
train_batch_size: 1
val_batch_size: 1
mixed_precision: "bf16"

report_to: tensorboard
gradient_accumulation_steps: 8
learning_rate: 4e-5

model_type: marigold

pretrained_model: depth-anything/Depth-Anything-V2-Large


max_grad_norm: 1.


multi_res_noise:
  strength: 0.9
  annealed: true
  downscale_strategy: original

gt_depth_type: depth_raw_norm
gt_mask_type: valid_mask_raw


loss:
  name: mse_loss
  kwargs:
    reduction: mean

lr_scheduler: constant_with_warmup
lr_warmup_steps: 500
# lr: 3.0e-05
# lr_scheduler:
#   name: IterExponential
#   kwargs:
#     total_iter: 25000
#     final_ratio: 0.01
#     warmup_steps: 100

# # Light setting for the in-training validation and visualization
validation:
  denoising_steps: 4
  ensemble_size: 1
  processing_res: 0
  match_input_res: false
  resample_method: bilinear
  main_val_metric: abs_relative_difference
  main_val_metric_goal: minimize
  init_seed: 2024

eval:
  alignment: least_square
  align_max_res: null
  eval_metrics:
  - abs_relative_difference
  - squared_relative_difference
  - rmse_linear
  - rmse_log
  - log10
  - delta1_acc
  - delta2_acc
  - delta3_acc
  - i_rmse
  - silog_rmse

num_train_epochs: 400