seed: 42

pretrained_model_name_or_path: cagliostrolab/animagine-xl-4.0

dataset_args:

  src_list:
    - sample_list: workspace/datasets/l2d_bodysamples_v3.txt
      sample_rate: 1
      
  target_size_groups:
    - ['head', 'front hair', 'back hair', 'headwear', 'face', 'irides', 'eyebrow', 'eyewhite', 'eyelash', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear']
    - ['topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 'tail', 'wings', 'objects']
    - ['front hair', 'back hair', 'head', 'headwear', 'face', 'irides', 'eyebrow', 'eyewhite', 'eyelash', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear', 'topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 'tail', 'wings', 'objects']
  mask_cond: false
  random_flip: 0.5
  random_pad_prob: 0.5
  target_size: 1024
  random_aug_mask: 0.0

  tag_list: [
    'head', 'front hair', 'back hair', 'headwear', 'face', 'irides', 'eyebrow', 'eyewhite', 'eyelash', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 
    'neck', 'neckwear', 'topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 
    'tail', 'wings', 'objects'
  ]

  mix_tag_prob: 0.000
  mix_tag_groups:
    - tags: ['hair', 'headwear', 'face', 'eyes', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 'neck', 'neckwear']
      random_tag_prob: 0.
      size_skip_tags: ['hair']
    - tags: ['topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 'tail', 'wings', 'objects']
      random_tag_prob: 0.


model_args:
  in_channels: 8

optimizer_args:
  betas: [0.9, 0.999]
  weight_decay: 0.01
  eps: 1e-08

lr_scheduler:
  constant_with_warmup

lr_warmup_steps: 500

validation_steps: 2000
checkpointing_steps: 4000
visualization_steps: 500
train_batch_size: 8
val_batch_size: 1
mixed_precision: "bf16"

# report_to: wandb
gradient_accumulation_steps: 1
learning_rate: 3e-5

use_8bit_adam: false
enable_xformers_memory_efficient_attention: true

checkpoints_total_limit: 10

max_train_steps: 200000

proportion_empty_prompts: 0.0
vae_use_offset_prob: 0.25
max_visualize_samples: 4

snr_gamma: 5.0

guidance_scale: 1.0