# set it to the converted unet dir
pretrained_unet: workspace/ckpt/layerdiff_pretrained_unetdir

seed: 64

pretrained_model_name_or_path: cagliostrolab/animagine-xl-4.0

dataset_args:

  src_list:
    - sample_list: workspace/datasets/l2d_bodysamples_v3.txt

  mask_cond: false
  random_flip: 0.5
  random_pad_prob: 0.5
  target_size: 1280
  include_blend_cls: false
  # pad_num_frames: 20
  ngroup_iters: 1
  pad_argb: false


  tag_list: [
    'head', 'front hair', 'back hair', 'headwear', 'face', 'irides', 'eyebrow', 'eyewhite', 'eyelash', 'eyewear', 'ears', 'earwear', 'nose', 'mouth', 
    'neck', 'neckwear', 'topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 
    'tail', 'wings', 'objects'
  ]

  mix_tag_groups:
    - tags: ['front hair', 'back hair', 'head', 'neck', 'neckwear', 'topwear', 'handwear', 'bottomwear', 'legwear', 'footwear', 'tail', 'wings', 'objects']
      random_tag_prob: 0.
    - tags: ['headwear', 'face', 'irides', 'eyebrow', 'eyewhite', 'eyelash', 'eyewear', 'ears', 'earwear', 'nose', 'mouth']
      random_tag_prob: 0.

model_args:
  in_channels: 8

optimizer_args:
  betas: [0.9, 0.999]
  weight_decay: 0.01
  eps: 1e-08

lr_scheduler:
  constant_with_warmup

lr_warmup_steps: 500

validation_steps: 2000
checkpointing_steps: 4000
visualization_steps: 125
train_batch_size: 1
val_batch_size: 1
mixed_precision: "bf16"

report_to: wandb
gradient_accumulation_steps: 8
learning_rate: 4e-5

use_8bit_adam: false
enable_xformers_memory_efficient_attention: true
gradient_checkpointing: true

checkpoints_total_limit: 10

max_train_steps: 200000

proportion_empty_prompts: 0.0
vae_use_offset_prob: 0.25
# max_visualize_samples: 4

learnable_parameters: all

temporal_lr:
  5000: 4e-5
  100000: 4e-5

guidance_scale: 1.0

snr_gamma: 5.0