seed: 42

pretrained_model_name_or_path: cagliostrolab/animagine-xl-4.0
pretrained_vae_model_name_or_path: null

train_trans_decoder: true
train_vae_decoder: false

noise_max_step: 1
noise_prob: 0.0
visualize_src: []

dataset_args:
  src_list:
    - sample_list: workspace/datasets/l2d_bodysamples_v3.txt
      sample_rate: 1
  target_size: 512

optimizer_args:
  betas: [0.9, 0.999]
  weight_decay: 0.01
  eps: 1e-08

lr_scheduler: constant_with_warmup
lr_warmup_steps: 10
train_batch_size: 1
mixed_precision: "no"
report_to: tensorboard
gradient_accumulation_steps: 1
learning_rate: 3e-5
max_train_steps: 100
validation_steps: 200
checkpointing_steps: 200
visualization_steps: 200
